### ISSUE TITLE
Request: Lumine NSFW Skin

### ISSUE THREAD

**Issue by ilovediluc** [zeroruka/GI_Assets#10]
I'm down horrendous

**Comment by zeroruka** [comment]
done

**Comment by abyss1103** [comment]
> 

裤子好像没完全去掉

**Comment by abyss1103** [comment]
> 完结

裤子还在

**Comment by ilovediluc** [comment]
can anything be done about the shorts under the dress?

**Comment by zeroruka** [comment]
I made it translucent, but the effect isn't that clear. There is no way of removing the bloomers without editing the model and there's no way of editing the model currently, sorry!

**Comment by SkylineMike** [comment]
is the file missing?

**Comment by zeroruka** [comment]
?
