### ISSUE TITLE
Warning Mod Duplicate

### ISSUE THREAD

**Issue by thienha1** [zeroruka/GI_Assets#100]
How to remore this warning or change any hash?
![Untitled](https://user-images.githubusercontent.com/18132856/180754850-34c492d3-e553-4c8c-82b9-07a944aa9d37.png)

**Comment by djjsns** [comment]
等个十秒左右他会自己消失

**Comment by iris10086** [comment]
In .ini file, there has some override about FaceHeadShadow.
You can delete them in ini file, and don't have bug in game.

**Comment by zeroruka** [comment]
fixed
