### ISSUE TITLE
为什么我用K打开原神后整个画面是泛白的呀，求大佬解答一下

### ISSUE THREAD

**Issue by Yuye0102** [zeroruka/GI_Assets#101]
![OT14@R5ZLM4_90AK_0FWPLI](https://user-images.githubusercontent.com/109961044/180768865-33c708f7-0a8c-48c0-ab17-8349832b5072.png)
我打开游戏就是这个白色，是我设置有问题吗？求大佬解答

**Comment by Yuye0102** [comment]
对了，还有神里·主角她们的裙子去不掉··也不知道是什么原因
![O``0FXUIQMGI(QQ$311ZF_R](https://user-images.githubusercontent.com/109961044/180769869-7641c69f-43ae-4b42-90b7-382b284e6be4.png)
麻烦大佬解答一下了，画面太白看的眼睛好痛

**Comment by djjsns** [comment]
在配置k那里，滑到最底下，会教你改文本。不过我改了还是白不知道是不是我的问题。神里还有几个皮肤是用不了的

**Comment by hxhxzd** [comment]
我超，勇士！这是官服吗！

**Comment by Yuye0102** [comment]
谢谢大佬解答，不过改裙子那边我在配置k哪里找不到所谓的[Macro.HUDToggle]条例，所以就不了了之了···还有泛白问题也无法解决，很难受

**Comment by Yuye0102** [comment]
> 我超，勇士！这是官服吗！

是，封了就算了，顺带脱坑

**Comment by hxhxzd** [comment]
我记得有个地方要改成Flase，但是忘了在哪hhh

**Comment by Yuye0102** [comment]
> 我记得有个地方要改成Flase，但是忘了在哪hhh
····太痛了

**Comment by djjsns** [comment]
> 

Ctrl➕f     文本搜索

**Comment by Yuye0102** [comment]
> 

我试过了，找不到，我现在自己建了一个，不知道起不起作用

**Comment by djjsns** [comment]
> > 
> 
> 我试过了，找不到，我现在自己建了一个，不知道起不起作用

你的路径跟他说的可能是不一样的，直接搜索那个文件就行了

**Comment by Yuye0102** [comment]
> > > 
> > 
> > 
> > 我试过了，找不到，我现在自己建了一个，不知道起不起作用
> 
> 你的路径跟他说的可能是不一样的，直接搜索那个文件就行了

我改了之后裙子问题解决了，除了神里，其他人裙子都没了，不过甘雨身体少了两块···感觉看起来瘆得慌，最重要的画面泛白问题还是没办法解决，找不到相对应的说明

**Comment by djjsns** [comment]
> > > > 
> > > 
> > > 
> > > 我试过了，找不到，我现在自己建了一个，不知道起不起作用
> > 
> > 
> > 你的路径跟他说的可能是不一样的，直接搜索那个文件就行了
> 
> 我改了之后裙子问题解决了，除了神里，其他人裙子都没了，不过甘雨身体少了两块···感觉看起来瘆得慌，最重要的画面泛白问题还是没办法解决，找不到相对应的说明

你想截图的话原神里面相机截出来是正常的，想玩或者其他可以转3dm目前没有发现太大问题

**Comment by fengyan11** [comment]
3dmigoto比sk好用，乳头啥的都有，sk就只有贴图

**Comment by fengyan11** [comment]
![X (I_N0R5$70I)M%3VOA(EY](https://user-images.githubusercontent.com/107903693/180803180-dc3dbd36-f2d3-4872-a36a-c8b13c8ebec6.png)

**Comment by Yuye0102** [comment]
> > 对了，还有神里·主角她们的裙子去不掉··也不知道是什么原因 ![O``0FXUIQMGI(QQ$311ZF_R](https://user-images.githubusercontent.com/109961044/180769869-7641c69f-43ae-4b42-90b7-382b284e6be4.png) 麻烦大佬解答一下了，画面太白看的眼睛好痛
> 
> 请看wiki https://github.com/zeroruka/GI-Assets-wiki/wiki/%E4%BD%BF%E7%94%A8-SpecialK#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

好的，谢谢，泛白问题已经解决了

**Comment by Yuye0102** [comment]
> 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图

大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封

**Comment by xinhailp** [comment]
> > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> 
> 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封

但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩

**Comment by xinhailp** [comment]
> > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> 
> 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封

凌华sk贴图就去掉了一个内裤，你自己做了去裙子了吗大佬，发我一个呗

**Comment by fengyan11** [comment]
> > > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> > 
> > 
> > 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封
> 
> 但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩

兄弟，理解不了你的脑回路，难道贴图比改模型更真啊？3dmigoto模型乳头和下面都有建模的，而sk只有贴图

> > > > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> > > 
> > > 
> > > 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封
> > 
> > 
> > 但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩
> 
> 兄弟，理解不了你的脑回路，难道贴图比改模型更真啊？3dmigoto模型乳头和下面都有建模的，而sk只有贴图

3dmigoto也能改成有一点衣服的，只不过zeroruka大佬只做过甘雨有黑丝袜的

**Comment by fengyan11** [comment]
> > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> 
> 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封

我是不建议官服用，我用过几次没被封

**Comment by shenmo7192** [comment]
> > > > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> > > 
> > > 
> > > 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封
> > 
> > 
> > 但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩
> 
> 兄弟，理解不了你的脑回路，难道贴图比改模型更真啊？3dmigoto模型乳头和下面都有建模的，而sk只有贴图

可能是说，如果所有人物都是全裸，那不就成了接头霸王了吗(

服装还是很有特色的，而且zeroruka佬改的色色服装大部分都不错（包括我最开始不太习惯的安柏V1现在反而看久了越看越喜欢甚至不用别的了），保留人物特色同时突出人物的性感区域，比如九条的奶盖下方改透气，安柏的腰和腿，还有优菈的臀，还有其实我个人的话觉得sk那个刻晴也挺有味道，在保留服装大部的情况下增强性感的地方是很棒的。官方的模型没有改动，虽然限制多一些，但是更贴合原版体验，会像一个人物穿色色服装但是发生的故事都一致的平行世界

至于效果，肯定是3DMijoto更强，但是现在模型并不是很全，比如安柏就没有对应的（在这里卑微求一个）....而且全裸是不是非常让人喜欢也是见仁见智，比如全裸刻晴做的非常精致，可是失去了主要特征(甚至cup都变了)可能就会有一些不真实感，有接头霸王的感觉，而且替换的模型在细节方面有瑕疵或者和官方不符也挺出戏。像甘雨的mijoto模型身体和头好像有点色差，飞行的时候模型还有点错位，这些都会导致和原本的提瓦特体验出现一定的隔阂

**Comment by xinhailp** [comment]
> > > > > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> > > > 
> > > > 
> > > > 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封
> > > 
> > > 
> > > 但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩
> > 
> > 
> > 兄弟，理解不了你的脑回路，难道贴图比改模型更真啊？3dmigoto模型乳头和下面都有建模的，而sk只有贴图
> 
> 可能是说，如果所有人物都是全裸，那不就成了接头霸王了吗(
> 
> 服装还是很有特色的，而且zeroruka佬改的色色服装大部分都不错（包括我最开始不太习惯的安柏V1现在反而看久了越看越喜欢甚至不用别的了），保留人物特色同时突出人物的性感区域，比如九条的奶盖下方改透气，安柏的腰和腿，还有优菈的臀，还有其实我个人的话觉得sk那个刻晴也挺有味道，在保留服装大部的情况下增强性感的地方是很棒的。官方的模型没有改动，虽然限制多一些，但是更贴合原版体验，会像一个人物穿色色服装但是发生的故事都一致的平行世界
> 
> 至于效果，肯定是3DMijoto更强，但是现在模型并不是很全，比如安柏就没有对应的（在这里卑微求一个）....而且全裸是不是非常让人喜欢也是见仁见智，比如全裸刻晴做的非常精致，可是失去了主要特征(甚至cup都变了)可能就会有一些不真实感，有接头霸王的感觉，而且替换的模型在细节方面有瑕疵或者和官方不符也挺出戏。像甘雨的mijoto模型身体和头好像有点色差，飞行的时候模型还有点错位，这些都会导致和原本的提瓦特体验出现一定的隔阂

是的，正解，觉得还是保留原有特色好

**Comment by fengyan11** [comment]
> > > > > 3dmigoto比sk好用，乳头啥的都有，sk就只有贴图
> > > > 
> > > > 
> > > > 大佬用这个模型打的官服上面吗？用了多久了，我有点担心用不了多久就被封
> > > 
> > > 
> > > 但是我觉得3d太假了，没有穿衣服有感觉，我也用的sk，官服玩
> > 
> > 
> > 兄弟，理解不了你的脑回路，难道贴图比改模型更真啊？3dmigoto模型乳头和下面都有建模的，而sk只有贴图
> 
> 可能是说，如果所有人物都是全裸，那不就成了接头霸王了吗(
> 
> 服装还是很有特色的，而且zeroruka佬改的色色服装大部分都不错（包括我最开始不太习惯的安柏V1现在反而看久了越看越喜欢甚至不用别的了），保留人物特色同时突出人物的性感区域，比如九条的奶盖下方改透气，安柏的腰和腿，还有优菈的臀，还有其实我个人的话觉得sk那个刻晴也挺有味道，在保留服装大部的情况下增强性感的地方是很棒的。官方的模型没有改动，虽然限制多一些，但是更贴合原版体验，会像一个人物穿色色服装但是发生的故事都一致的平行世界
> 
> 至于效果，肯定是3DMijoto更强，但是现在模型并不是很全，比如安柏就没有对应的（在这里卑微求一个）....而且全裸是不是非常让人喜欢也是见仁见智，比如全裸刻晴做的非常精致，可是失去了主要特征(甚至cup都变了)可能就会有一些不真实感，有接头霸王的感觉，而且替换的模型在细节方面有瑕疵或者和官方不符也挺出戏。像甘雨的mijoto模型身体和头好像有点色差，飞行的时候模型还有点错位，这些都会导致和原本的提瓦特体验出现一定的隔阂

sk只有贴图看起来有点别扭，尤其是侧着看和看下面
