### ISSUE TITLE
[REQUEST] Amber 3Dmigoto Skin

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI_Assets#103]
Tried to convert from special k one but not really know how to.....

**Comment by zeroruka** [comment]
If you are only trying to convert the texture, then you can just copy ovee the dds file from sk to 3dm character directory, and then export genshin mod folder in blender. So for Amber, you will need the amber character files from [GI model importer assets](https://github.com/SilentNightSound/GI-Model-Importer-Assets), and replace Amberbodylightmap and amberbodydiffuse with the corresponding dds textures from sk.

**Comment by shenmo7192** [comment]
> If you are only trying to convert the texture, then you can just copy ovee the dds file from sk to 3dm character directory, and then export genshin mod folder in blender.
> 
> So for Amber, you will need the amber character files from [GI model importer assets](https://github.com/SilentNightSound/GI-Model-Importer-Assets), and replace Amberbodylightmap and amberbodydiffuse with the corresponding dds textures from sk.

I'll try it and make an PR

Wish for a new skin for amber on 3dmigoto too XD

**Comment by shenmo7192** [comment]
> If you are only trying to convert the texture, then you can just copy ovee the dds file from sk to 3dm character directory, and then export genshin mod folder in blender.
> 
> So for Amber, you will need the amber character files from [GI model importer assets](https://github.com/SilentNightSound/GI-Model-Importer-Assets), and replace Amberbodylightmap and amberbodydiffuse with the corresponding dds textures from sk.

Error occured when try to export

![图片](https://user-images.githubusercontent.com/47873776/180970870-a1659ffd-c8bc-4a8b-a037-e5cd326006a7.png)

Tried to add `import sys` in the start of the file, which makes blender crash when try to export

**Comment by zeroruka** [comment]
update your script and try again

**Comment by shenmo7192** [comment]
> update your script and try again

https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6

Got the script from the wiki....

It's modified for the anime game so it's hard to find another version.....

**Comment by shenmo7192** [comment]
> update your script and try again

Got solution. 

I think the wiki is not very clear, things like you should change the export file name to character name or you should export the project to the very folder you importedd is not mentioned and cause confusing errors

I'll try to convert and make an pull request. 

P.S. Sincerely expect new skin for Amber on 3DMigoto
