### ISSUE TITLE
[REQUEST]希望可以提供当前刻晴的Blender模型

### ISSUE THREAD

**Issue by hxhxzd** [zeroruka/GI_Assets#104]
如题，希望可以提供当前刻晴的Blender模型，想要研究研究

**Comment by shenmo7192** [comment]
blender可以直接导入
需要插件
详情见wiki插件，装好之后可以导入

**Comment by hxhxzd** [comment]
> blender可以直接导入 需要插件 详情见wiki插件，装好之后可以导入

可以说一下是哪个插件吗，名字就行，这好多.py找不着啊qwq

**Comment by shenmo7192** [comment]
> > blender可以直接导入 需要插件 详情见wiki插件，装好之后可以导入
> 
> 可以说一下是哪个插件吗，名字就行，这好多.py找不着啊qwq

https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6

**Comment by hxhxzd** [comment]
感谢

**Comment by fengyan11** [comment]
> 感谢

导入成功了没？

**Comment by fengyan11** [comment]
> > > blender可以直接导入 需要插件 详情见wiki插件，装好之后可以导入
> > 
> > 
> > 可以说一下是哪个插件吗，名字就行，这好多.py找不着啊qwq
> 
> https://github.com/SilentNightSound/GI-Model-Importer/blob/main/CN_README.md#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97-3dmigoto-blender-%E6%8F%92%E4%BB%B6

怎么安装插件啊，看那教程看不懂

**Comment by abyss1103** [comment]
反正我是导不进去

**Comment by zeroruka** [comment]
https://github.com/zeroruka/GI_Assets/blob/main/Mods/3Dmigoto/Mods%20(nsfw)/Keqing/Keqing.blend
