### ISSUE TITLE
[GENERAL] Maybe delete the Models with textures folder or move it to another repository and run git gc to decline the size of the repository ?

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI_Assets#107]
The total size of this repo is 900+MB and it cost TONS OF vpn traffic to clone 😭

**Comment by shenmo7192** [comment]
> https://minhaskamal.github.io/DownGit/#/home
> 
> Use this to only download subdirectories.

Made a mirror in Gitee to make it convenient for CN Users

https://shenmo7192.gitee.io/downgit/

**Comment by UID-503058116** [comment]
《关于两个国人都以为对面是老外然后飙英语这件事》

**Comment by shenmo7192** [comment]
> 《关于两个国人都以为对面是老外然后飙英语这件事》

https://github.com/zeroruka/GI-Assets/issues/150#issuecomment-1217874007

**Comment by UID-503058116** [comment]
> > 《关于两个国人都以为对面是老外然后飙英语这件事》
> 
> [#150 (comment)](https://github.com/zeroruka/GI-Assets/issues/150#issuecomment-1217874007)
![QQ图片20220822202145](https://user-images.githubusercontent.com/37666214/185920109-7f112153-34ae-44b7-868f-3221e17a4df5.jpg)
