### ISSUE TITLE
GI_Assets/Mods/3Dmigoto/Mods (nsfw)/Kuki Shinobu/SKV1/ skin doesn't work

### ISSUE THREAD

**Issue by lineageosUs** [zeroruka/GI_Assets#108]
I put the mod under Mods folder as usual, and after pressing F1 it doesn't work

**Comment by zeroruka** [comment]
press F10

**Comment by hnoaman-rep0** [comment]
I wanted to write "press F10", that was a mistake, the mod doesn't load, test it yourself with 3Dmigoto!

**Comment by 2636532975** [comment]
我这也是，按F10也没用，还是原皮。难道国际服不兼容？

**Comment by shenmo7192** [comment]
Well I think I mess it up....
It doesn't work on me too, but I don't know why

**Comment by EnesUgurlu** [comment]
For me as well, all the others work except for this one

**Comment by zeroruka** [comment]
Should be fixed now, please check.

**Comment by EnesUgurlu** [comment]
Thank you! It works now
