### ISSUE TITLE
Please make a yunjin NSFW skin, thank you very much

### ISSUE THREAD

**Issue by DPW1122** [zeroruka/GI_Assets#11]

**Comment by zeroruka** [comment]
鞋子不能改短，需要改模型的都不行。其他的都可以，

![](https://i.imgur.com/e25Wpo6_d.webp?maxwidth=760&fidelity=grand)

> 能一条腿穿袜子另一条腿光腿当然最好

红色圈的部分保留袜子，其余的光腿是吗？

**Comment by abyss1103** [comment]
> 鞋子不能改短，需要改模型的都不行。其他的都可以，
> 
> ![](https://camo.githubusercontent.com/2c7431c91f7e5245870e846fb5bf25c0bdf4674cdd5f6eccc7817287402fb42a/68747470733a2f2f692e696d6775722e636f6d2f65323557706f365f642e776562703f6d617877696474683d37363026666964656c6974793d6772616e64)
> 
> > 能一条腿穿袜子另一条腿光腿当然最好
> 
> 红色圈的部分保留袜子，其余的光腿是吗？

对

**Comment by abyss1103** [comment]
> 鞋子不能改短，需要改模型的都不行。其他的都可以，
> 
> ![](https://camo.githubusercontent.com/2c7431c91f7e5245870e846fb5bf25c0bdf4674cdd5f6eccc7817287402fb42a/68747470733a2f2f692e696d6775722e636f6d2f65323557706f365f642e776562703f6d617877696474683d37363026666964656c6974793d6772616e64)
> 
> > 能一条腿穿袜子另一条腿光腿当然最好
> 
> 红色圈的部分保留袜子，其余的光腿是吗？

如果可以的话希望之前甘雨和原皮芭芭拉包括刻晴以后的角色也可以这样，非常感谢

**Comment by zeroruka** [comment]
云堇不能一半光腿，他的两个腿用的是同一个贴图

![image](https://user-images.githubusercontent.com/89210318/175220119-f37dc2a4-36d8-4121-a799-4a2fcee771b0.png)

**Comment by zeroruka** [comment]
done

**Comment by abyss1103** [comment]
> 云堇不能一半光腿，他的两个腿用的是同一个贴图
> 
> ![image](https://user-images.githubusercontent.com/89210318/175220119-f37dc2a4-36d8-4121-a799-4a2fcee771b0.png)

OK，这样也行谢谢
