### ISSUE TITLE
[GENERAL]3dm修改bodydiffuse.dds角色身体为什么会变黑

### ISSUE THREAD

**Issue by yikaluosai** [zeroruka/GI_Assets#110]
想给其他角色加yin纹，就像琴菲谢尔那种
学着在bodydiffuse里面加，但是加进去之后进游戏角色只有加的位置有图案，其他位置全黑而且图案的位置也不对，位置不对我大概能理解，建模变了，但是角色身体为什么会变黑啊，不能理解。。。。。
另外，blender怎么加载已经改过的建模啊，想在已经改过的基础上再改，我看攻略只学会了怎么加载最初始的建模，重头开始改起太难受了啊。。。。。

**Comment by iris10086** [comment]
感觉说的不是很清楚。
不如截图看看。
另外，已经导出的xxxmod文件好像没有vb文件应该不能直接用。
修改的话可以改那些带了工程文件的。比如甘雨的Ver2，ayaka ver2。里面都附带有工程文件。

**Comment by yikaluosai** [comment]
感谢回答
身体变黑的问题已经解决了，是没有反转透明度的原因，我又看了一遍教程改好了已经
