### ISSUE TITLE
[REQUEST]麻烦大佬调整一下雷神的3Dmigoto mod，把上衣去掉最好。

### ISSUE THREAD

**Issue by Radminister** [zeroruka/GI_Assets#113]

**Comment by azklkjl** [comment]
感觉留着袖子和下体裙子会更好，全果的话留个袖子也行，我只是提个建议，大佬想弄就弄

**Comment by manhongfeiqing** [comment]
我也想跪求大佬做个全裸雷神

**Comment by manhongfeiqing** [comment]
我重新组织一下语言，跪求大佬做个果体雷神

**Comment by UID-503058116** [comment]
怎么closed了 
今天又出了新issue，也是要雷神果体的
这个将军涩涩 看来是刚需了
![Snipaste：Snipper - Snipaste：2022-08-17：13-04-51](https://user-images.githubusercontent.com/37666214/185040474-798cf8bd-6647-4c05-bc1f-73c1e736719e.png)
