### ISSUE TITLE
[BUG]Some files are corrupted and garbled

### ISSUE THREAD

**Issue by asqkl1** [zeroruka/GI_Assets#116]
Ayaka：ver1，ver2→AyakaExtra.ib
Eula：ver2→EulaDress.ib
Fischl：→FischlExtra.ib
Ganyu：ver1→GanyuDress.ib
ver2→GanyuExtra.ib
Keqing：→KeqingDress.ib
Ningguang：→NingguangDress.ib
Noelle：→NoelleExtra.ib
Sara：→KujouSaraExtra.ib
TravellerGirl：ver2→TravelerGirlDress.ib
Xiangling：ver1，ver2→XianglingExtra.ib
Yae：ver1→YaeExtra.ib，ver2→YaeDress.ib，YaeExtra.ib
Yelan：→YelanExtra.ib
Yoimiya：→YoimiyaExtra.ib
YunJin：ver1→YunJinExtra.ib

**Comment by manhongfeiqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
