### ISSUE TITLE
[BUG]部分文件损坏出现乱码，无法下载

### ISSUE THREAD

**Issue by asqkl1** [zeroruka/GI_Assets#117]
神里绫华的两个版本的AyakaExtra.ib
尤拉的版本2的EulaDress.ib
菲谢尔的FischlExtra.ib
甘雨版本1的GanyuDress.ib
甘雨版本2的GanyuExtra.ib
刻晴的KeqingDress.ib
凝光的NingguangDress.ib
诺艾尔的NoelleExtra.ib
莹妹版本2的TravelerGirlDress.ib
香菱版本1的XianglingExtra.ib
香菱版本2的XianglingExtra.ib
八重神子版本1的YaeExtra.ib
八重神子版本2的YaeExtra.ib，YaeDress.ib
夜阑的YelanExtra.ib
宵宫的YoimiyaExtra.ib
云堇版本1的YunJinExtra.ib

**Comment by luoluojialuo** [comment]
不是bug 省事可以下zip

**Comment by zeroruka** [comment]
不想全下的话，用下面的工具下载单个文件夹
https://minhaskamal.github.io/DownGit/#/home 或 https://shenmo7192.gitee.io/downgit/

**Comment by asqkl1** [comment]
好的，已解决，谢谢
