### ISSUE TITLE
叉腰动作时手臂弯曲还有手臂是不是太粗了[BUG]

### ISSUE THREAD

**Issue by fengyan11** [zeroruka/GI_Assets#118]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fengyan11** [comment]
如图
![image](https://user-images.githubusercontent.com/107903693/182027767-beb63b5b-f3ee-4710-b8bd-4800c7b3b62f.png)

**Comment by abyss1103** [comment]
手臂粗细还好吧，只是这弯曲确实看得

**Comment by yunshuiyaogu** [comment]
那个，我想知道为什么我下不起鸭，可以帮帮我吗

**Comment by yunshuiyaogu** [comment]
可以的话加个微信或者qq好嘛

**Comment by yunshuiyaogu** [comment]
> 手臂粗细还好吧，只是这弯曲确实看得

为什么我下不起鸭，能帮帮我吗，可以的话加个微信或者qq好嘛

**Comment by fengyan11** [comment]
> > 手臂粗细还好吧，只是这弯曲确实看得
> 
> 为什么我下不起鸭，能帮帮我吗，可以的话加个微信或者qq好嘛

用谷歌浏览器下载GitZIp for github这个扩展程序就行了

**Comment by yunshuiyaogu** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zeroruka/GI_Assets"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 上午7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zeroruka/GI_Assets] 叉腰动作时手臂弯曲还有手臂是不是太粗了[BUG] (Issue #118)





   
手臂粗细还好吧，只是这弯曲确实看得
  
为什么我下不起鸭，能帮帮我吗，可以的话加个微信或者qq好嘛
  
用谷歌浏览器下载GitZIp for github这个扩展程序就行了

**Comment by luoluojialuo** [comment]
我通过拼接其他人分享的blend后改出来的模型 在游戏里拼接而来的模型会有棕色的沟边，比游戏原本的黑色沟边要粗一倍，这个要怎么去除？我看你的截图似乎没有这个现象。

**Comment by fengyan11** [comment]
> 我通过拼接其他人分享的blend后改出来的模型 在游戏里拼接而来的模型会有棕色的沟边，比游戏原本的黑色沟边要粗一倍，这个要怎么去除？我看你的截图似乎没有这个现象。

是回复我的吗？我不会拼接模型啊

**Comment by azklkjl** [comment]
不过从下面看臀部有种莫名其妙的感觉，感觉有点方

**Comment by zeroruka** [comment]
已修复
