### ISSUE TITLE
求宵宫的全清凉版本

### ISSUE THREAD

**Issue by Sunben4869** [zeroruka/GI_Assets#125]
求宵宫全裸并且裸足的版本可以吗

**Comment by fengyan11** [comment]
裸足可能满足不了，毕竟脚趾头和指甲盖都要做，估计很难，只要能做成刻晴那种水准我就满足了。

**Comment by Sunben4869** [comment]
好的好的，裸足做不了就算了吧，能更加清凉点就可以

**Comment by fengyan11** [comment]
> 好的好的，裸足做不了就算了吧，能更加清凉点就可以

应该能做裸足的，我昨天找到了

**Comment by fengyan11** [comment]
![Uploading -3dd472e1070c472d.png…]()

**Comment by fengyan11** [comment]
![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)

**Comment by mlgbqmzzf** [comment]
> ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)

大佬在哪找到的，这个好棒

**Comment by fengyan11** [comment]
> > ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)
> 
> 大佬在哪找到的，这个好棒

油管上一个大佬做的，叫王何惜

**Comment by mlgbqmzzf** [comment]
> > > ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)
> > 
> > 
> > 大佬在哪找到的，这个好棒
> 
> 油管上一个大佬做的，叫王何惜

作者是找到了，可是mod在哪下载，感谢大佬

**Comment by fengyan11** [comment]
> > > > ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)
> > > 
> > > 
> > > 大佬在哪找到的，这个好棒
> > 
> > 
> > 油管上一个大佬做的，叫王何惜
> 
> 作者是找到了，可是mod在哪下载，感谢大佬

视频下面就有啊，点开简介就有下载链接

**Comment by mlgbqmzzf** [comment]
> > > > > ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)
> > > > 
> > > > 
> > > > 大佬在哪找到的，这个好棒
> > > 
> > > 
> > > 油管上一个大佬做的，叫王何惜
> > 
> > 
> > 作者是找到了，可是mod在哪下载，感谢大佬
> 
> 视频下面就有啊，点开简介就有下载链接

没有youtube账号看不了，也注册不了，大佬能否分享一下mod？感谢感谢

**Comment by fengyan11** [comment]
> > > > > > ![-3dd472e1070c472d](https://user-images.githubusercontent.com/107903693/182506544-561a3f58-c017-40b5-80a2-d4de51da76ed.png)
> > > > > 
> > > > > 
> > > > > 大佬在哪找到的，这个好棒
> > > > 
> > > > 
> > > > 油管上一个大佬做的，叫王何惜
> > > 
> > > 
> > > 作者是找到了，可是mod在哪下载，感谢大佬
> > 
> > 
> > 视频下面就有啊，点开简介就有下载链接
> 
> 没有youtube账号看不了，也注册不了，大佬能否分享一下mod？感谢感谢

没有账号也能下载，我就是在网页版油管上找到的

**Comment by Sunben4869** [comment]
谢谢大佬
