### ISSUE TITLE
[Bug] 国服被和谐的模型无法被正常覆盖

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI_Assets#13]
使用SK启动官服，发现经过国服和谐过的模型未被覆盖（受影响角色：安柏 罗莎莉亚（目前被搞的四个就这俩有皮肤））

请在后续更新中补充这两个的模型替换

另：开sk玩了一天，目前为止未被封号，可以来这里打卡看存活日期

**Comment by rayshire** [comment]
你开心就好

**Comment by shenmo7192** [comment]
因使用 Global模式，可以使用 https://gitee.com/Best_Chen/skin-revert 启动启动器。
