### ISSUE TITLE
请做一个丽莎 NSFW皮肤，非常感谢

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#14]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by zeroruka** [comment]
完成，皮肤是由 Modder4869#4818 做的

**Comment by abyss1103** [comment]
> 完成，皮肤是由 Modder4869#4818 做的

感谢
