### ISSUE TITLE
脚本代码使用能再详细一点吗，非常感谢

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gen-LLL** [comment]
请问2.7版本的游戏是不能使用melonloader吗？我安装了melonloader，但启动游戏时报错如下：
[INTERNAL FAILURE] Failed to Find Mono Library!

**Comment by rayshire** [comment]
only 2.6

**Comment by Gen-LLL** [comment]
换成2.6了也报一样的错

**Comment by rayshire** [comment]
你的melon的问题

**Comment by Gen-LLL** [comment]
我用的是官方下载的installer呀

**Comment by rayshire** [comment]
你猜你为什么用不了

**Comment by Gen-LLL** [comment]
真心求教，我折腾半天了也没好

**Comment by rayshire** [comment]
https://github.com/lassedds/melonloader-animegaming（五分钟后删）

**Comment by rayshire** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

**Comment by rayshire** [comment]
done [this]
(https://github.com/zeroruka/GI_Assets/blob/main/Scripts/ray/README.md)
