### ISSUE TITLE
[GENERAL]如此清晰的wiki太难得了，能否对mod修改方法做详细介绍？

### ISSUE THREAD

**Issue by cuppasama** [zeroruka/GI_Assets#18]
先致以谢意。
但皮肤这东西众口难调，我就更喜欢不那么nsfw的。但自行修改时，对于衣着的定位、光照图层的知识不足，难以做出可用的mod。我随手一改，人物全身都在发光了。
建议对于如何做好mod的细节，做出进一步的介绍。
再表感谢。

**Comment by cuppasama** [comment]
已经自行学习了解，请关闭这个thread吧

**Comment by UID-503058116** [comment]
巧了 刚开始我也是人物全身发光 后来问题是diffise忘记添加alpha
