### ISSUE TITLE
[BUG] Noelle skin ver2

### ISSUE THREAD

**Issue by Phantomzone24** [zeroruka/GI_Assets#19]
**Describe the bug**
在游戏里看到的诺艾尔皮肤跟preview的预览图不一样，裙子还是很长

**To Reproduce**

**Expected behavior**

**Screenshots**
![mmexport1655691686468](https://user-images.githubusercontent.com/107709768/174514065-e0f608b7-e108-4ef4-a122-f18410b4f948.png)

**Additional context**

**Comment by zeroruka** [comment]
裙子要自己改，不是通过贴图去掉的

请看[这里](https://github.com/zeroruka/GI-Assets-wiki/wiki/%E6%9B%B4%E6%94%B9%E6%B8%B2%E6%9F%93#%E5%8E%BB%E8%A3%99)

**Comment by Phantomzone24** [comment]
解决了，谢谢！
