### ISSUE TITLE
Hu tao NSFW skin plz [REQUEST]

### ISSUE THREAD

**Issue by roszzz** [zeroruka/GI_Assets#21]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by zeroruka** [comment]
its hard to make since she is all covered by her clothes, ill see what I can do

**Comment by abyss1103** [comment]
> its hard to make since she is all covered by her clothes, ill see what I can do

如果可以的话这个建议弄个全半透明

**Comment by abyss1103** [comment]
> its hard to make since she is all covered by her clothes, ill see what I can do

多加个黑丝货白丝也行
