### ISSUE TITLE
甘雨去除裙子模型会缺失，请问怎么解决，非常感谢。

### ISSUE THREAD

**Issue by fengyan11** [zeroruka/GI_Assets#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by fengyan11** [comment]
![7fc7edb0a9b11ff0](https://user-images.githubusercontent.com/107903693/174714084-0989411a-6c2b-485d-8ac8-77d51036c22c.png)

**Comment by zeroruka** [comment]
sk没法解决

**Comment by fengyan11** [comment]
可是预览图里的就没有缺失啊

**Comment by zeroruka** [comment]
那个是2.6用melon去的，2.7用不了melon
