### ISSUE TITLE
[GENERAL] 建议 安柏 NFSW模型添加只露腰不修改胸部和裤子的版本

### ISSUE THREAD

**Issue by shenmo7192** [zeroruka/GI_Assets#25]
安柏的配色决定改一个完美的涩涩模型似乎是不太容易的

现在的模型在使用的时候有些奇怪的地方，最明显的是跑图的时候从后面看屁股的颜色变了一块就很奇怪。。。而且改的颜色也很微妙。。。好像 shit in pants :cry: 

然后胸部的更改，似乎打乱了配色的平衡，棕灰色的罩子比较奇怪，在那里原本不是这个颜色

如果没有更好的方案，个人的建议是推出一个只露腰的版本，这样会比较和谐

---
也可能单纯是我的XP问题 :joy_cat:

**Comment by zeroruka** [comment]
完成

**Comment by sonichy** [comment]
不要丝袜，不要腿上的绑带！

**Comment by shenmo7192** [comment]
> 不要丝袜，不要腿上的绑带！

要改的话腿环还是要的吧，米家传统XP(小声bb

**Comment by zeroruka** [comment]
丝袜改掉会很怪，有建模。腿环也不行，同样原因
