### ISSUE TITLE
[REQUEST]求做一个行秋的mod，虽然这听来有点怪？？？总之，万分感谢！！！

### ISSUE THREAD

**Issue by zifeiyutu** [zeroruka/GI_Assets#27]

**Comment by fengyan11** [comment]
兄弟，你有点怪啊，是要有大屌那种还是？我不会做，只是问一下

**Comment by abyss1103** [comment]
??行秋的这位我是真想不明白

**Comment by fengyan11** [comment]
男角色的腿偏细没有女角色的腿有肉感，估计做出来也不好看，除非能换一双腿，而且又胸又平…

**Comment by shenmo7192** [comment]
是想要扶她还是娘化还是小男孩
帖主性别？

**Comment by fengyan11** [comment]
怎么，你打算做一个?

**Comment by abyss1103** [comment]
> 怎么，你打算做一个?

…行秋这话题结束好吗，已经closed了，没意义的东西少讲🤔

**Comment by shenmo7192** [comment]
> 怎么，你打算做一个?

没那个能力，但是还是有兴趣了解一下帖主理想中的NSFW的行秋大概是什么样子

感觉应该是类似五郎本子一样的状态，大概是要保持男性的

但是这个性器官大概不好做吧？改模不太能搞吧

**Comment by zifeiyutu** [comment]
> > 怎么，你打算做一个?
> 
> 没那个能力，但是还是有兴趣了解一下帖主理想中的NSFW的行秋大概是什么样子
> 
> 感觉应该是类似五郎本子一样的状态，大概是要保持男性的
> 
> 但是这个性器官大概不好做吧？改模不太能搞吧

层主xp虽然是futa，但是做这个确实不现实

**Comment by yejunjie10311031** [comment]
需要男角色去衣物模型的请见我自己开的项目https://github.com/yejunjie10311031/GI-Assets-homo

**Comment by yejunjie10311031** [comment]
> > 怎么，你打算做一个?
> 
> 没那个能力，但是还是有兴趣了解一下帖主理想中的NSFW的行秋大概是什么样子
> 
> 感觉应该是类似五郎本子一样的状态，大概是要保持男性的
> 
> 但是这个性器官大概不好做吧？改模不太能搞吧

使用blender和3dmigoto可以实现制作性器官的模型
![kazuha-1](https://user-images.githubusercontent.com/62139629/176994742-a9022a10-101a-4dfc-85a5-e8b016784097.png)
![Genshin Impact 2022_7_2 13_19_27](https://user-images.githubusercontent.com/62139629/176994766-5a15ecd0-9c50-4a30-a829-8bca3cb715ae.png)
![kazuha-3](https://user-images.githubusercontent.com/62139629/176994781-b72a9a01-e1e3-426f-9a97-1fbd0f9b31b9.png)

**Comment by zifeiyutu** [comment]
> > > 怎么，你打算做一个?
> > 
> > 
> > 没那个能力，但是还是有兴趣了解一下帖主理想中的NSFW的行秋大概是什么样子
> > 感觉应该是类似五郎本子一样的状态，大概是要保持男性的
> > 但是这个性器官大概不好做吧？改模不太能搞吧
> 
> 使用blender和3dmigoto可以实现制作性器官的模型 ![kazuha-1](https://user-images.githubusercontent.com/62139629/176994742-a9022a10-101a-4dfc-85a5-e8b016784097.png) ![Genshin Impact 2022_7_2 13_19_27](https://user-images.githubusercontent.com/62139629/176994766-5a15ecd0-9c50-4a30-a829-8bca3cb715ae.png) ![kazuha-3](https://user-images.githubusercontent.com/62139629/176994781-b72a9a01-e1e3-426f-9a97-1fbd0f9b31b9.png)

你是我的英雄！！！

**Comment by shenmo7192** [comment]
> 

兄啊你的XP好解包怪(

期待成品

**Comment by yejunjie10311031** [comment]
@shenmo7192 @zifeiyutu 行秋的做好了,来https://github.com/yejunjie10311031/GI-Assets-homo下载文件,用3dmigoto加载.
![xingqiu-1](https://user-images.githubusercontent.com/62139629/177004831-b97a7e60-fbd0-4d9f-b0eb-146f3fd0029e.png)
![xingqiu-2](https://user-images.githubusercontent.com/62139629/177004836-f824fc90-364b-46fa-82b5-de04f730e0a6.png)
![xingqiu-4](https://user-images.githubusercontent.com/62139629/177004837-c9c14797-cc27-4e79-8ed8-434035f5b7e9.png)
![xingqiu-3](https://user-images.githubusercontent.com/62139629/177004838-c619cd80-49be-4144-8ca4-b144c6379dfa.png)

**Comment by abyss1103** [comment]
> > > 怎么，你打算做一个?
> > 
> > 
> > 没那个能力，但是还是有兴趣了解一下帖主理想中的NSFW的行秋大概是什么样子
> > 感觉应该是类似五郎本子一样的状态，大概是要保持男性的
> > 但是这个性器官大概不好做吧？改模不太能搞吧
> 
> 使用blender和3dmigoto可以实现制作性器官的模型 ![kazuha-1](https://user-images.githubusercontent.com/62139629/176994742-a9022a10-101a-4dfc-85a5-e8b016784097.png) ![Genshin Impact 2022_7_2 13_19_27](https://user-images.githubusercontent.com/62139629/176994766-5a15ecd0-9c50-4a30-a829-8bca3cb715ae.png) ![kazuha-3](https://user-images.githubusercontent.com/62139629/176994781-b72a9a01-e1e3-426f-9a97-1fbd0f9b31b9.png)

那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏

**Comment by fengyan11** [comment]
> > > > 怎么，你打算做一个？
> > > 
> > > 
> > > 那个地方，但是还是有兴趣了解帖主理想
> > > 的
> > > 情况活动能搞吧
> > 
> > 
> > 使用blender和3dmigoto可以实现制作性器官的模型![一叶-1](https://user-images.githubusercontent.com/62139629/176994742-a9022a10-101a-4dfc-85a5-e8b016784097.png) ![原神影响 2022_7_2 13_19_27](https://user-images.githubusercontent.com/62139629/176994766-5a15ecd0-9c50-4a30-a829-8bca3cb715ae.png) ![一叶3](https://user-images.githubusercontent.com/62139629/176994781-b72a9a01-e1e3-426f-9a97-1fbd0f9b31b9.png)
> 
> 那你能做个八重神子吗，那个胸看得真难受，如果可以请把头像和针缝还有（请加点红润）组成来，非常感谢🙏

加我一个，八重的还有刻晴的胸看得是真难受，没有乳沟

**Comment by abyss1103** [comment]
> > > > > 怎么，你打算做一个？
> > > > 
> > > > 
> > > > 那个地方，但是还是有兴趣了解帖主理想
> > > > 的
> > > > 情况活动能搞吧
> > > 
> > > 
> > > 使用blender和3dmigoto可以实现制作性器官的模型![一叶-1](https://user-images.githubusercontent.com/62139629/176994742-a9022a10-101a-4dfc-85a5-e8b016784097.png) ![原神影响 2022_7_2 13_19_27](https://user-images.githubusercontent.com/62139629/176994766-5a15ecd0-9c50-4a30-a829-8bca3cb715ae.png) ![一叶3](https://user-images.githubusercontent.com/62139629/176994781-b72a9a01-e1e3-426f-9a97-1fbd0f9b31b9.png)
> > 
> > 
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把头像和针缝还有（请加点红润）组成来，非常感谢🙏
> 
> 加我一个，八重的还有刻晴的胸看得是真难受，没有乳沟

不行，作者乳沟也做不出来

**Comment by zeroruka** [comment]
> 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏

做好了

**Comment by abyss1103** [comment]
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏
> 
> 做好了

Thanks，you are my hero！

**Comment by fengyan11** [comment]
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸和针缝还有（请加点红润）组成来，非常感谢🙏
> 
> 做好了

大佬nb 甘雨的能不能做？非常感谢

**Comment by abyss1103** [comment]
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏
> 
> 做好了

等以后您想做琴,胡桃,凌华和刻晴了记得把胸加大点👍

**Comment by abyss1103** [comment]
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏
> 
> 做好了

能把甘雨的神之眼和丝袜弄回来吗，全果未免单调了些

**Comment by abyss1103** [comment]
> > 那你能做个八重神子吗，那个胸看得真难受，如果可以请把胸轮廓和乳头还有缝（请加点红润）做出来，非常感谢🙏
> 
> 做好了

能做个云堇吗?丝袜部分就是筒袜的，然后最好能把最外面那件披风保留和加大胸部，非常感谢🙏
