### ISSUE TITLE
[REQUEST]求做一个不一样的宵宫 嘻嘻嘻  万分感谢

### ISSUE THREAD

**Issue by timoxiaokai** [zeroruka/GI_Assets#30]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by abyss1103** [comment]
还能怎么不一样，你这概念太含糊了点

**Comment by zeroruka** [comment]
完成
