### ISSUE TITLE
[GENERAL]

### ISSUE THREAD

**Issue by yogurt416** [zeroruka/GI_Assets#37]
如何找到图2的页面
![2A3C4B64-BAA5-48A9-B394-81CDDC6027F5](https://user-images.githubusercontent.com/107999955/175331508-67563a4f-31ac-4a23-b876-4aebc16cb540.png)
![AC6E3405-1842-4C04-A7A8-44A306DABDF5](https://user-images.githubusercontent.com/107999955/175331864-9d73b443-8dc9-41c2-b0e5-80c73af20304.png)

**Comment by zeroruka** [comment]
render mod tools 里

**Comment by yogurt416** [comment]
> render mod tools 里

但是按下shift+ctrl+backspace后只有图里的选项
![F4EAB381-F012-458A-8A5B-1B20BDC77C81](https://user-images.githubusercontent.com/107999955/175440283-8c191dde-7a5d-41b0-9b5b-27855e12b124.png)

**Comment by zeroruka** [comment]
。。。你倒是展开啊，就在Direct3D 11 Settings 里

**Comment by yogurt416** [comment]
找到了，谢谢
