### ISSUE TITLE
为什么裙子消不掉呢？[GENERAL]

### ISSUE THREAD

**Issue by yint54** [zeroruka/GI_Assets#41]
比如女仆的第三版和云瑾的第二版

**Comment by abyss1103** [comment]
我好几个character base点了都没去裙子，所有角色都去不了

**Comment by fengyan11** [comment]
你没点对，是可以去裙子的，只不过有几个角色去不了

**Comment by abyss1103** [comment]
> 

有好几个我一个一个也试过了，全部点也试过了，看着教程弄的啊，宵宫都去不了

**Comment by fengyan11** [comment]
![Uploading 1af18a092fed06b7.png…]()

**Comment by yogurt416** [comment]
把那个hide inactive关了，有好多base，你得一个个试，我试了一个小时才点到对的

**Comment by zeroruka** [comment]
不用关hide inactive，你可以在角色界面找，会比较快

**Comment by abyss1103** [comment]
> 不用关hide inactive，你可以在角色界面找，会比较快

没用……

**Comment by yogurt416** [comment]
有很多个，你要一个个试，很考验耐心

**Comment by abyss1103** [comment]
> 有很多个，你要一个个试，很考验耐心

我好像确实一个个都试过了，是点了那个base就直接会消失吗还是得点never

**Comment by yogurt416** [comment]
需要点never

**Comment by yint54** [comment]
> 

可以具体说一下在哪里设置吗？谢谢

**Comment by luoluojialuo** [comment]
人直接黑掉 衣服全在 人直接黑掉

**Comment by BlacK201** [comment]
hide inactive勾上，按C进入角色界面，base就那么三四个左右，一个一个试选对就好了…选错了角色的其它部分就会黑掉

**Comment by BlacK201** [comment]
hide inactive勾上，按C进入角色界面，base就那么三四个左右，一个一个试选对就好了…选错了角色的其它部分就会黑掉

**Comment by abyss1103** [comment]
> hide inactive勾上，按C进入角色界面，base就那么三四个左右，一个一个试选对就好了…选错了角色的其它部分就会黑掉

我就俩个，一个没效果一个人物都消失了

**Comment by luoluojialuo** [comment]
發完留言就弄明白了，他那個SK的滾輪有點不清楚，光標要放在有never draw的那一邊才能滾動，一個女角色少說也有三個Base。其中兩三個Base勾掉就可以了。

**Comment by abyss1103** [comment]
> 發完留言就弄明白了，他那個SK的滾輪有點不清楚，光標要放在有never draw的那一邊才能滾動，一個女角色少說也有三個Base。其中兩三個Base勾掉就可以了。



> 發完留言就弄明白了，他那個SK的滾輪有點不清楚，光標要放在有never draw的那一邊才能滾動，一個女角色少說也有三個Base。其中兩三個Base勾掉就可以了。

我能看到底，那也就没办法往下滚动吧，滚动方法我也知道
