### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by fgtqz** [zeroruka/GI_Assets#56]
I know this is not a skin request but if you have a model replacing script for melon could you post it?

**Comment by zeroruka** [comment]
Model replacement for melon use [ModelChanger](https://github.com/portra400nc/ModelChanger). For importing obj files use [this](https://cdn.discordapp.com/attachments/974357717198188605/974454582799392808/objV2.cs) script.

**Comment by fgtqz** [comment]
Sorry for reopening this but is there anyway you can import a custom rigged model into the game without 3dmigoto?

**Comment by zeroruka** [comment]
nope, 3dmigoto is the only way of importing rigged models
