### ISSUE TITLE
ganyu ver2 应用在3dmigoto里全身比较暗蓝，没有浏览图效果，求解，非常感谢

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#60]

**Comment by abyss1103** [comment]
![屏幕截图 2022-07-03 225847](https://user-images.githubusercontent.com/107688386/177045525-bc6faa38-82a7-4fb1-8d07-9a4de709b743.png)

**Comment by abyss1103** [comment]
> ![屏幕截图 2022-07-03 225847](https://user-images.githubusercontent.com/107688386/177045525-bc6faa38-82a7-4fb1-8d07-9a4de709b743.png)

如图

**Comment by abyss1103** [comment]
> 我也用的3dmigoto ![image](https://user-images.githubusercontent.com/28262013/177156784-efae655a-ee2e-43b9-bc1e-5e2810ad3507.png)

你把把甘雨mod放进去做了什么

**Comment by abyss1103** [comment]
> 我也用的3dmigoto ![image](https://user-images.githubusercontent.com/28262013/177156784-efae655a-ee2e-43b9-bc1e-5e2810ad3507.png)

我把原来的两个贴图删了换了这个对应的一个贴图，就成这样了

**Comment by WQ3465802** [comment]
> 

那你可能缺少一个显示高亮阴影的贴图，在ver1里有这个贴图

**Comment by WQ3465802** [comment]
不用mod，去裙子后腰部会镂空缺少一块

**Comment by abyss1103** [comment]
> > 
> 
> 那你可能缺少一个显示高亮阴影的贴图，在ver1里有这个贴图

ver1里的那个不是光腿的吗

**Comment by WQ3465802** [comment]
> > > 
> > 
> > 
> > 那你可能缺少一个显示高亮阴影的贴图，在ver1里有这个贴图
> 
> ver1里的那个不是光腿的吗

试试看呗，不清楚

**Comment by abyss1103** [comment]
> > > > 
> > > 
> > > 
> > > 那你可能缺少一个显示高亮阴影的贴图，在ver1里有这个贴图
> > 
> > 
> > ver1里的那个不是光腿的吗
> 
> 试试看呗，不清楚

OK，I solved it.

**Comment by abyss1103** [comment]
问题解决
