### ISSUE TITLE
求夜兰NSFW皮肤 胸罩和衣服蕾丝部分保留版本，非常感谢

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#64]
裤子就把裆那块皮裤去掉就行，胸请把罩子保留，跟菲谢尔的丝袜修复版本差不多

**Comment by zeroruka** [comment]
你自己试着改一下呗

**Comment by abyss1103** [comment]
> 你自己试着改一下呗

我不会改🤔能教我也可以，我现在把好多贴图都换成18+图片，以及npc的胸部我也在改，但我没有阴和屁眼图。角色模型教我改就行，我也想学，非常感谢

**Comment by abyss1103** [comment]
> 你自己试着改一下呗

这样的话正好我有一堆像改的

**Comment by abyss1103** [comment]
> 你自己试着改一下呗

我也正好有一堆想改的

**Comment by luoluojialuo** [comment]
有中文教程 看你想法很多，不自己动手屈才了。

**Comment by abyss1103** [comment]
> 有中文教程 看你想法很多，不自己动手屈才了。

求直达链接😲

**Comment by abyss1103** [comment]
> 你自己试着改一下呗

我在Twitter上找到了这个https://twitter.com/Hexilucky/status/1543437188418846720?cxt=HHwWgICqzcD8sesqAAAA   他的三篇文章雷神 琴 莫娜 详见。可见现在是有方法改的，今天您出的九条也是个很好的例子。希望能出一期教程，非常感谢
