### ISSUE TITLE
[REQUEST] 能做个优菈的光腿版本吗，感谢

### ISSUE THREAD

**Issue by Phantomzone24** [zeroruka/GI_Assets#65]
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by abyss1103** [comment]
优菈的裤筒和鞋子是连在一起的，如果要把裤筒去掉那么鞋子那部分会看起来很奇怪，如果把鞋子那部分当袜子那么这袜子又很奇怪。如果你只单单要光腿明天我可以给你做，但除了光腿以外我会添加别的贴图

**Comment by Gen-LLL** [comment]
好兄弟，做一个康康

**Comment by abyss1103** [comment]
> 好兄弟，做一个康康

明天有时间的话就做

**Comment by abyss1103** [comment]
[Eula.zip](https://github.com/zeroruka/GI_Assets/files/9088968/Eula.zip)
优菈的腿上边被裤袋勒紧了，模型是凹进去的，所以上面保留了

**Comment by Phantomzone24** [comment]
要改模型就没办法了，多谢

**Comment by srgdtgd** [comment]
1
