### ISSUE TITLE
请求女士（变身前）nsfw皮肤，非常感谢🙏

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#67]
我没看到女士的模型，但贴图根本不知道从何下手

**Comment by djjsns** [comment]
能不能做一个尤拉的全裸，或者去多些衣服，万分感谢🙏🏻🙏🏻🙏🏻🙏🏻

**Comment by shenmo7192** [comment]
> 能不能做一个尤拉的全裸，或者去多些衣服，万分感谢🙏🏻🙏🏻🙏🏻🙏🏻

3Dmigoto里面有
