### ISSUE TITLE
[BUG]涩涩里面的文件下不了，怎么解决啊老板，VPN什么问题啊，求解决啊

### ISSUE THREAD

**Issue by srgdtgd** [zeroruka/GI_Assets#79]
求解决 老板  vpn什么问题呢

**Comment by zeroruka** [comment]
我不知道，你不要问了

**Comment by srgdtgd** [comment]
呜呜呜，不会弄呀  哎呀

**Comment by abyss1103** [comment]
> 求解决 老板 vpn什么问题呢

vpn如果速度慢反而更没用，建议下个Steam++，把github有关全部开启，这样稍微会好一点

**Comment by srgdtgd** [comment]
> > 求解决 老板 vpn什么问题呢
> 
> vpn如果速度慢反而更没用，建议下个Steam++，把github有关全部开启，这样稍微会好一点

哪里下，哥们。你是什么下载文件的哥们哥们

**Comment by abyss1103** [comment]
> > > 求解决 老板 vpn什么问题呢
> > 
> > 
> > vpn如果速度慢反而更没用，建议下个Steam++，把github有关全部开启，这样稍微会好一点
> 
> 哪里下，哥们。你是什么下载文件的哥们哥们

这个真得自己找

**Comment by abyss1103** [comment]
> > > > > 求解决 老板 vpn什么问题呢
> > > > 
> > > > 
> > > > vpn如果速度慢反而更没用，建议下个Steam++，把github有关全部开启，这样稍微会好一点
> > > 
> > > 
> > > 哪里下，哥们。你是什么下载文件的哥们哥们
> > 
> > 
> > 这个真得自己找
> 
> 我没有电脑vpn 就正常打开文件下载就无法访问 ，不知道去哪里找电脑vpn

……这个b站上搜一下大把多
