### ISSUE TITLE
[GENERAL]新版本凌华  夜兰  莫纳 的skin建模不显示没有效果

### ISSUE THREAD

**Issue by xinhailp** [zeroruka/GI_Assets#80]
凌华 夜兰  莫纳 瑟瑟去衣没有效果

**Comment by abyss1103** [comment]
> 凌华 夜兰 莫纳 瑟瑟去衣没有效果

自己用specialk先把贴图导出再覆盖

**Comment by abyss1103** [comment]
有些角色的贴图不知道是什么改过了，我也有好多显示不出来

**Comment by xinhailp** [comment]
> 有些角色的贴图不知道是什么改过了，我也有好多显示不出来

guan服可以玩mod还是贴图

**Comment by abyss1103** [comment]
> > 有些角色的贴图不知道是什么改过了，我也有好多显示不出来
> 
> guan服可以玩mod还是贴图

都可以啊

**Comment by xinhailp** [comment]
> > > 有些角色的贴图不知道是什么改过了，我也有好多显示不出来
> > 
> > 
> > guan服可以玩mod还是贴图
> 
> 都可以啊

都不封号吗

**Comment by xinhailp** [comment]
> > > 有些角色的贴图不知道是什么改过了，我也有好多显示不出来
> > 
> > 
> > guan服可以玩mod还是贴图
> 
> 都可以啊

mod和贴图什么区别呢

**Comment by abyss1103** [comment]
> > > > 有些角色的贴图不知道是什么改过了，我也有好多显示不出来
> > > 
> > > 
> > > guan服可以玩mod还是贴图
> > 
> > 
> > 都可以啊
> 
> 都不封号吗

……那不行，会被封，两个都会被。我以为你说的是客户端而已，区别自己多了解就行，我一时说不清，再具体的问题别问了，再问就变性质了

**Comment by xinhailp** [comment]
> 

嗯嗯好，大佬你有原神瑟瑟贴图吗，我不知道怎么自己做

**Comment by xinhailp** [comment]
> > > > > 有些角色的贴图不知道是什么改过了，我也有好多显示不出来
> > > > 
> > > > 
> > > > guan服可以玩mod还是贴图
> > > 
> > > 
> > > 都可以啊
> > 
> > 
> > 都不封号吗
> 
> ……那不行，会被封，两个都会被。我以为你说的是客户端而已，区别自己多了解就行，我一时说不清，再具体的问题别问了，再问就变性质了

嗯嗯好，大佬你有原神瑟瑟贴图吗，我不知道怎么自己做

**Comment by abyss1103** [comment]
https://github.com/zeroruka/GI_Assets/wiki/Creating-Skins

**Comment by xinhailp** [comment]
> 

不会做，第一次弄呢

**Comment by abyss1103** [comment]
https://github.com/zeroruka/GI_Assets/wiki
这里面有全部教程
自己慢慢搞，摸鱼可不能只为了回你可以自己学会的东西

**Comment by xinhailp** [comment]
> https://github.com/zeroruka/GI_Assets/wiki 这里面有全部教程 自己慢慢搞，摸鱼可不能只为了回你可以自己学会的东西

那什么，可以加你个wx或扣扣不，大佬

**Comment by zeroruka** [comment]
> 凌华 夜兰 莫纳 瑟瑟去衣没有效果

用国际客户端

**Comment by xinhailp** [comment]
> > 凌华 夜兰 莫纳 瑟瑟去衣没有效果
> 
> 用国际客户端

玩的国服2.8没效果

**Comment by zeroruka** [comment]
所以用国际客户端啊。我没国服客户端，没法测试，国服都是和谐过的。你要是想玩国服那你自己找hash值，改一下就好了

**Comment by abyss1103** [comment]
> > > 凌华 夜兰 莫纳 瑟瑟去衣没有效果
> > 
> > 
> > 用国际客户端
> 
> 玩的国服2.8没效果

所以说叫你把贴图贴一遍就好

**Comment by xinhailp** [comment]
> > > > 凌华 夜兰 莫纳 瑟瑟去衣没有效果
> > > 
> > > 
> > > 用国际客户端
> > 
> > 
> > 玩的国服2.8没效果
> 
> 所以说叫你把贴图贴一遍就好

不会弄呀，大佬，能给我发个新版本凌华 莫娜贴图吗  国服
