### ISSUE TITLE
Collei's NSFW skin

### ISSUE THREAD

**Issue by abyss1103** [zeroruka/GI_Assets#81]
[Collei.zip](https://github.com/zeroruka/GI_Assets/files/9125437/Collei.zip)
zeroka帮我放一下谢谢啦。裤和内衣好像都有很薄一层建模，边角纹理还残留，不过影响不大

**Comment by abyss1103** [comment]
少了个ru

**Comment by WQ3465802** [comment]
大佬牛逼啊，测试服的吗？

**Comment by abyss1103** [comment]
> 大佬牛逼啊，测试服的吗？

测试服难抢

**Comment by WQ3465802** [comment]
> > 大佬牛逼啊，测试服的吗？
> 
> 测试服难抢
测试服改的私服吗？
测试服客户端哪下载的？

**Comment by zeroruka** [comment]
已添加

**Comment by zeroruka** [comment]
> 测试服改的私服吗？
> 测试服客户端哪下载的？

不要在这问测试服相关的问题
