### ISSUE TITLE
国服2.8莫娜皮肤多处bug[BUG]

### ISSUE THREAD

**Issue by 1008611wu** [zeroruka/GI_Assets#82]
![20220717112333](https://user-images.githubusercontent.com/109206500/179382527-1c3e2546-2b60-44f6-bc3e-5f083f8fe511.png)
![20220717112314](https://user-images.githubusercontent.com/109206500/179382529-7628e4e1-3e26-4cf7-8589-dad762bcedb3.png)
难道是要玩旧版本么QWQ

**Comment by zeroruka** [comment]
你用的是莫娜的服装吗

**Comment by 2855743931** [comment]
> 

用的是莫娜服装，旧的服装没有改动，还是迪迦那套衣服

**Comment by xinhailp** [comment]
> > 
> 
> 用的是莫娜服装，旧的服装没有改动，还是迪迦那套衣服

玩的关方国服2.8吗

**Comment by 2855743931** [comment]
> > > 
> > 
> > 
> > 用的是莫娜服装，旧的服装没有改动，还是迪迦那套衣服
> 
> 玩的关方国服2.8吗

嗯对的

**Comment by 2855743931** [comment]
> 你用的是莫娜的服装吗

用的是莫娜服装，旧的服装没有改动，还是迪迦那套衣服

**Comment by fengyan11** [comment]
> 你用的是莫娜的服装吗

是和谐的那套衣服 星与月之约那套 有bug

**Comment by zeroruka** [comment]
https://github.com/SilentNightSound/GI-Model-Importer/releases/tag/v5.0

更新一下3dmigoto试试

**Comment by 1008611wu** [comment]
> https://github.com/SilentNightSound/GI-Model-Importer/releases/tag/v5.0
> 
> 更新一下3dmigoto试试

可以了，用最新3dm就行了
