### ISSUE TITLE
[BUG]The mona 3dmigoto mod added today has a bug.

### ISSUE THREAD

**Issue by xiaoyaoqingchun** [zeroruka/GI_Assets#83]
There is a bug in the display of the new mona 3dmigoto mod in the game today. It doesn't match the preview pictures.

**Comment by xiaoyaoqingchun** [comment]
![20220717140407](https://user-images.githubusercontent.com/67886621/179386189-ea676892-1c51-4358-ba39-44bafb42d163.png)

**Comment by xiaoyaoqingchun** [comment]
![image](https://user-images.githubusercontent.com/67886621/179386316-b5d64307-36bb-4550-ba35-ee6b46929058.png)

**Comment by zeroruka** [comment]
duplicate of #82 

Update your 3dmigoto to latest version.
