### ISSUE TITLE
Scripts文件夹如何使用？

### ISSUE THREAD

**Issue by weirdo1275** [zeroruka/GI_Assets#88]
希望有个详细的办法。2.6UE的c#控制台百度半天最后在melonloader那里卡住了实在不知道如何搞了。希望大佬指教

**Comment by zeroruka** [comment]
> 使用方法：在2.6UE的c#控制台粘贴编译即可（要改的角色放在队伍里但不要切换上场，去裙效果传送失效）

**Comment by zeroruka** [comment]
melon没有的话自己在别的地方找，各种discord群里都有，这里不会提供melon下载

**Comment by weirdo1275** [comment]
下载自动安装后，选择Genshin impact.exe 安装完成，启动Genshin impact.exe 没反应怎么办大佬

**Comment by weirdo1275** [comment]
> 必须用原神专用的melon

谢谢您
