### ISSUE TITLE
[REQUEST]请求大佬给个国服更新后的凌华莫娜贴图

### ISSUE THREAD

**Issue by xinhailp** [zeroruka/GI_Assets#89]
求求大佬们给个2.8更新后的凌华莫娜贴图，不会改hash值和制作皮肤，求求了

**Comment by zeroruka** [comment]
不会就学，改hash很难吗？教程资源都在那里，我就不明白是哪里不会。自己折腾一会都是能搞定的，要是自己不读教程，懒得搞，那就是你自己的问题了。还有就是能不能不要开多个同样的issue，issue #86 里我已经讲了如何找hash，issue #80 里也有人给你教程。。。

![image](https://user-images.githubusercontent.com/89210318/179483153-b6610c29-0346-4867-a997-6cf6ffea8087.png)

我有空再修国服贴图

**Comment by xinhailp** [comment]
> 不会就学，改hash很难吗？教程资源都在那里，我就不明白是哪里不会。自己折腾一会都是能搞定的，要是自己不读教程，懒得搞，那就是你自己的问题了。还有就是能不能不要开多个同样的issue，issue #86 里我已经讲了如何找hash，issue #80 里也有人给你教程。。。
> 
> ![image](https://user-images.githubusercontent.com/89210318/179483153-b6610c29-0346-4867-a997-6cf6ffea8087.png)
> 
> 我有空再修国服贴图

我看了，并且也下载了所有软件，但是打开导入图片我就蒙了，啥也不会了，没有教程了，有的话我肯定想自己弄呢，真的没有其他教程了，我想学也不会呀，我每个教程都认真看了的

**Comment by xinhailp** [comment]
> https://github.com/zeroruka/GI-Assets-wiki/wiki/%E5%88%9B%E5%BB%BA%E7%9A%AE%E8%82%A4#%E5%AF%BC%E5%87%BA%E8%B4%B4%E5%9B%BE
> 
> 只看导出贴图的部分，其他不要管。导出的dds 8字符的名字就是hash，也就是Compressed_ 后面的是hash。把那个hash记住，重命名你要改的dds文件就好了。比如你导出的是莫娜的diffuse，那么hash就是莫娜的 diffuse，你也就要重命名莫娜的diffuse dds。导出哪个就重命名哪个。
> 
> ![image](https://user-images.githubusercontent.com/89210318/179488671-8260c741-c7cc-4703-a579-27df6af2ebaf.png)
> 
> 但其实也不需要导出。看下图
> 
> ![image](https://user-images.githubusercontent.com/89210318/179489244-7e6e640d-7469-4375-90ea-45233484a7ba.png)
> 
> 黄色圈的就是hash值，重命名dds成那个hash就可以了。大小写没有影响。

谢谢谢谢，会了，大佬，但是只有一个hash值一个角色不是两个文件吗

**Comment by zeroruka** [comment]
cn就是国服客户端

**Comment by xinhailp** [comment]
> cn就是国服客户端

嗯嗯，谢啦，让你操心了，昨天用你教的已经会了，就是凌华只去掉了内裤，其他没有变化

**Comment by xinhailp** [comment]
> cn就是国服客户端

然后还有就是琴和罗莎我昨天改hash后人物贴图是黑的，人物身体变黑了

**Comment by xinhailp** [comment]
> cn就是国服客户端

安柏也是

**Comment by shenmo7192** [comment]
> 

安柏的我已经推pr合并了，不用改，直接用就行了
Amber(CN)和Amber(Alter)
单推人(
