### ISSUE TITLE
[GENERAL] 我在做凝光皮肤去衣过程遇到的问题，

### ISSUE THREAD

**Issue by iris10086** [zeroruka/GI_Assets#93]
去衣完之后测试发现有点问题。
技术有限无法解决。
来问问大佬。
![凝光mod问题](https://user-images.githubusercontent.com/93846901/180619543-c7bd665c-3b1b-4481-9b23-11be38027921.png)

**Comment by abyss1103** [comment]
怎么把贴图与模型在Blender里连接啊，导入模型没颜色都不知道该怎么改

**Comment by zeroruka** [comment]
> 去衣完之后测试发现有点问题。 技术有限无法解决。 来问问大佬

改lightmap了吗

**Comment by zeroruka** [comment]
> 怎么把贴图与模型在Blender里连接啊，导入模型没颜色都不知道该怎么改

https://www.youtube.com/watch?v=SC_Z0sMPsxs

**Comment by iris10086** [comment]
改了lightmap。背光没有异常。对光会异常。

**Comment by abyss1103** [comment]
> 改了lightmap。背光没有异常。对光会异常。

是不是没把lightmap光图反转

**Comment by abyss1103** [comment]
或者说漫反射图反转

**Comment by iris10086** [comment]
lightmap我改了，我感觉没问题。
我给工程文件放我自己的项目里了。
[工程文件](https://github.com/iris10086/GI_Assets/blob/temp/Mods/3Dmigoto/Mods%20(nsfw)/NingguangOrchid/NingguangOrchid.blend)
我应该解决不了了。技术有限。

**Comment by abyss1103** [comment]
> > 怎么把贴图与模型在Blender里连接啊，导入模型没颜色都不知道该怎么改
> 
> https://www.youtube.com/watch?v=SC_Z0sMPsxs

光照贴图要导入吗

**Comment by zeroruka** [comment]
> 光照贴图要导入吗

不要

**Comment by hohonb** [comment]
> 改了lightmap。背光没有异常。对光会异常。
![模型未贴合 PNG](https://user-images.githubusercontent.com/110122395/181904118-256c92b4-6823-475d-9061-5994d8a4ed65.jpg)
![上模型](https://user-images.githubusercontent.com/110122395/181904121-35cc230c-fc52-47d4-b687-930faa66d4fb.PNG)
![下模型](https://user-images.githubusercontent.com/110122395/181904122-eb435b5d-453e-4cd5-894d-6e09fdac31da.PNG)
![重叠](https://user-images.githubusercontent.com/110122395/181904123-b23ed4e9-2c6d-47f5-b355-ef11fd7e1daf.PNG)

不知道是不是这个问题，只是猜想。望各位大佬看看，本人不太会改模型，上下模型重合过后也不知道要不要改贴图，ini文件。
