### ISSUE TITLE
能不能做一个尤拉的全裸🤤🤤🤤

### ISSUE THREAD

**Issue by djjsns** [zeroruka/GI_Assets#97]
万分感谢

**Comment by iris10086** [comment]
我做了一个这个。正在上传。
不知道符不符合你的意思。
![preview](https://user-images.githubusercontent.com/93846901/180698793-52ebd2fb-ec1f-438c-b952-a09d11867f75.png)

**Comment by djjsns** [comment]
合！快传大哥，万分感谢

**Comment by iris10086** [comment]
> 合！快传大哥，万分感谢

等合并。
